package module.vennplot;

import java.io.InputStream;

import egps2.frame.ModuleFace;
import egps2.modulei.IInformation;
import egps2.modulei.IModuleLoader;
import egps2.modulei.IconBean;
import egps2.modulei.ModuleClassification;
import egps2.modulei.ModuleVersion;

public class MyModuleLoader implements IModuleLoader,IInformation {

	@Override
	public String getTabName() {
		return "Venn plot";
	}

	@Override
	public String getShortDescription() {
		return "A user-friendly tool for drawing venn diagram.";
	}

	@Override
	public ModuleVersion getVersion() {
		return new ModuleVersion(0, 0, 1);
	}

	@Override
	public IconBean getIcon() {
		InputStream resourceAsStream = getClass().getResourceAsStream("gui/vennPlot.svg");
		IconBean iconBean = new IconBean();
		iconBean.setSVG(true);
		iconBean.setInputStream(resourceAsStream);
		return iconBean;
	}

	@Override
	public ModuleFace getFace() {
			return new VennPlotMain(this);
	}

	@Override
	public int[] getCategory() {
		int[] ret = ModuleClassification.getOneModuleClassification(

				ModuleClassification.BYFUNCTIONALITY_COMPLICATED_VISUALIZATION_INDEX,
				ModuleClassification.BYAPPLICATION_VISUALIZATION_INDEX,
				ModuleClassification.BYCOMPLEXITY_LEVEL_5_INDEX,
				ModuleClassification.BYDEPENDENCY_FULL_FEATURES_INVOKED
				);
		return ret;
	}

	@Override
	public String getWhatDataInvoked() {
		return "Data is imported by the VOICM input frame";
	}

	@Override
	public String getSummaryOfResults() {
		return "The venn plot is generated by the eGPS software, it provides three sytle(text representation, classic venn plot and upset plot).";
	}
}
